# Generated by Django 5.1.7 on 2025-03-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('Address', models.TextField(max_length=200)),
                ('Resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
    ]
