# Generated by Django 5.1.7 on 2025-03-26 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_job_list_delete_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_list',
            new_name='Job',
        ),
    ]
