# Generated by Django 5.1.7 on 2025-04-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userdetails_phone_number_userdetails_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='Resume',
            new_name='resume',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='job_preference',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Freelance', 'Freelance')], max_length=100, null=True),
        ),
    ]
