# Generated by Django 5.1.7 on 2025-04-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_resume_userdetails_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='Profile_picture',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
