# Generated by Django 5.1.7 on 2025-04-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userdetails_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
