# Generated by Django 5.1.7 on 2025-04-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userdetails_is_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='is_recruiter',
        ),
    ]
