# Generated by Django 5.1.7 on 2025-04-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_userdetails_is_recruiter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
