# Generated by Django 5.1.7 on 2025-04-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
