# Generated by Django 5.1.7 on 2025-04-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship')], default='full_time', max_length=50),
        ),
    ]
