# Generated by Django 5.1.7 on 2025-04-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_jobpost_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
