# Generated by Django 5.1.7 on 2025-05-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='founded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
